//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDataServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bank", Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class Bank : object
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankDetails", Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class BankDetails : object
    {
        
        private string BankField;
        
        private string IfscField;
        
        private string MicrCodeField;
        
        private string BranchField;
        
        private string StdCodeField;
        
        private string ContactField;
        
        private string CityField;
        
        private string DistrictField;
        
        private string StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Bank
        {
            get
            {
                return this.BankField;
            }
            set
            {
                this.BankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Ifsc
        {
            get
            {
                return this.IfscField;
            }
            set
            {
                this.IfscField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MicrCode
        {
            get
            {
                return this.MicrCodeField;
            }
            set
            {
                this.MicrCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Branch
        {
            get
            {
                return this.BranchField;
            }
            set
            {
                this.BranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StdCode
        {
            get
            {
                return this.StdCodeField;
            }
            set
            {
                this.StdCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Contact
        {
            get
            {
                return this.ContactField;
            }
            set
            {
                this.ContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string District
        {
            get
            {
                return this.DistrictField;
            }
            set
            {
                this.DistrictField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://arctechinfo.com/webservies/worldline-training", ConfigurationName="BankDataServiceReference.BankDataSoap")]
    public interface BankDataSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://arctechinfo.com/webservies/worldline-training/GetBankList", ReplyAction="*")]
        System.Threading.Tasks.Task<BankDataServiceReference.GetBankListResponse> GetBankListAsync(BankDataServiceReference.GetBankListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://arctechinfo.com/webservies/worldline-training/GetBranchDetailsByIfsc", ReplyAction="*")]
        System.Threading.Tasks.Task<BankDataServiceReference.GetBranchDetailsByIfscResponse> GetBranchDetailsByIfscAsync(BankDataServiceReference.GetBranchDetailsByIfscRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://arctechinfo.com/webservies/worldline-training/GetBranchDetailsByBank", ReplyAction="*")]
        System.Threading.Tasks.Task<BankDataServiceReference.GetBranchDetailsByBankResponse> GetBranchDetailsByBankAsync(BankDataServiceReference.GetBranchDetailsByBankRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBankListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBankList", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public BankDataServiceReference.GetBankListRequestBody Body;
        
        public GetBankListRequest()
        {
        }
        
        public GetBankListRequest(BankDataServiceReference.GetBankListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class GetBankListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int offset;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int rowCount;
        
        public GetBankListRequestBody()
        {
        }
        
        public GetBankListRequestBody(int offset, int rowCount)
        {
            this.offset = offset;
            this.rowCount = rowCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBankListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBankListResponse", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public BankDataServiceReference.GetBankListResponseBody Body;
        
        public GetBankListResponse()
        {
        }
        
        public GetBankListResponse(BankDataServiceReference.GetBankListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class GetBankListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankDataServiceReference.Bank[] GetBankListResult;
        
        public GetBankListResponseBody()
        {
        }
        
        public GetBankListResponseBody(BankDataServiceReference.Bank[] GetBankListResult)
        {
            this.GetBankListResult = GetBankListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBranchDetailsByIfscRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBranchDetailsByIfsc", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public BankDataServiceReference.GetBranchDetailsByIfscRequestBody Body;
        
        public GetBranchDetailsByIfscRequest()
        {
        }
        
        public GetBranchDetailsByIfscRequest(BankDataServiceReference.GetBranchDetailsByIfscRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class GetBranchDetailsByIfscRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ifscCode;
        
        public GetBranchDetailsByIfscRequestBody()
        {
        }
        
        public GetBranchDetailsByIfscRequestBody(string ifscCode)
        {
            this.ifscCode = ifscCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBranchDetailsByIfscResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBranchDetailsByIfscResponse", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public BankDataServiceReference.GetBranchDetailsByIfscResponseBody Body;
        
        public GetBranchDetailsByIfscResponse()
        {
        }
        
        public GetBranchDetailsByIfscResponse(BankDataServiceReference.GetBranchDetailsByIfscResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class GetBranchDetailsByIfscResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankDataServiceReference.BankDetails GetBranchDetailsByIfscResult;
        
        public GetBranchDetailsByIfscResponseBody()
        {
        }
        
        public GetBranchDetailsByIfscResponseBody(BankDataServiceReference.BankDetails GetBranchDetailsByIfscResult)
        {
            this.GetBranchDetailsByIfscResult = GetBranchDetailsByIfscResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBranchDetailsByBankRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBranchDetailsByBank", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public BankDataServiceReference.GetBranchDetailsByBankRequestBody Body;
        
        public GetBranchDetailsByBankRequest()
        {
        }
        
        public GetBranchDetailsByBankRequest(BankDataServiceReference.GetBranchDetailsByBankRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class GetBranchDetailsByBankRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bankName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int offset;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int rowCount;
        
        public GetBranchDetailsByBankRequestBody()
        {
        }
        
        public GetBranchDetailsByBankRequestBody(string bankName, int offset, int rowCount)
        {
            this.bankName = bankName;
            this.offset = offset;
            this.rowCount = rowCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBranchDetailsByBankResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBranchDetailsByBankResponse", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public BankDataServiceReference.GetBranchDetailsByBankResponseBody Body;
        
        public GetBranchDetailsByBankResponse()
        {
        }
        
        public GetBranchDetailsByBankResponse(BankDataServiceReference.GetBranchDetailsByBankResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class GetBranchDetailsByBankResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankDataServiceReference.BankDetails[] GetBranchDetailsByBankResult;
        
        public GetBranchDetailsByBankResponseBody()
        {
        }
        
        public GetBranchDetailsByBankResponseBody(BankDataServiceReference.BankDetails[] GetBranchDetailsByBankResult)
        {
            this.GetBranchDetailsByBankResult = GetBranchDetailsByBankResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface BankDataSoapChannel : BankDataServiceReference.BankDataSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class BankDataSoapClient : System.ServiceModel.ClientBase<BankDataServiceReference.BankDataSoap>, BankDataServiceReference.BankDataSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BankDataSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BankDataSoapClient.GetBindingForEndpoint(endpointConfiguration), BankDataSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankDataSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BankDataSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankDataSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BankDataSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankDataServiceReference.GetBankListResponse> BankDataServiceReference.BankDataSoap.GetBankListAsync(BankDataServiceReference.GetBankListRequest request)
        {
            return base.Channel.GetBankListAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankDataServiceReference.GetBankListResponse> GetBankListAsync(int offset, int rowCount)
        {
            BankDataServiceReference.GetBankListRequest inValue = new BankDataServiceReference.GetBankListRequest();
            inValue.Body = new BankDataServiceReference.GetBankListRequestBody();
            inValue.Body.offset = offset;
            inValue.Body.rowCount = rowCount;
            return ((BankDataServiceReference.BankDataSoap)(this)).GetBankListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankDataServiceReference.GetBranchDetailsByIfscResponse> BankDataServiceReference.BankDataSoap.GetBranchDetailsByIfscAsync(BankDataServiceReference.GetBranchDetailsByIfscRequest request)
        {
            return base.Channel.GetBranchDetailsByIfscAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankDataServiceReference.GetBranchDetailsByIfscResponse> GetBranchDetailsByIfscAsync(string ifscCode)
        {
            BankDataServiceReference.GetBranchDetailsByIfscRequest inValue = new BankDataServiceReference.GetBranchDetailsByIfscRequest();
            inValue.Body = new BankDataServiceReference.GetBranchDetailsByIfscRequestBody();
            inValue.Body.ifscCode = ifscCode;
            return ((BankDataServiceReference.BankDataSoap)(this)).GetBranchDetailsByIfscAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankDataServiceReference.GetBranchDetailsByBankResponse> BankDataServiceReference.BankDataSoap.GetBranchDetailsByBankAsync(BankDataServiceReference.GetBranchDetailsByBankRequest request)
        {
            return base.Channel.GetBranchDetailsByBankAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankDataServiceReference.GetBranchDetailsByBankResponse> GetBranchDetailsByBankAsync(string bankName, int offset, int rowCount)
        {
            BankDataServiceReference.GetBranchDetailsByBankRequest inValue = new BankDataServiceReference.GetBranchDetailsByBankRequest();
            inValue.Body = new BankDataServiceReference.GetBranchDetailsByBankRequestBody();
            inValue.Body.bankName = bankName;
            inValue.Body.offset = offset;
            inValue.Body.rowCount = rowCount;
            return ((BankDataServiceReference.BankDataSoap)(this)).GetBranchDetailsByBankAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BankDataSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BankDataSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BankDataSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44352/WebServicesDev/BankData.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BankDataSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44352/WebServicesDev/BankData.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BankDataSoap,
            
            BankDataSoap12,
        }
    }
}
